---
title: "Quantile Mapping Adjustment of AK ASOS Wind Speeds"
output: pdf_document
---

```{r setup}
library(knitr)
library(qmap)
library(dplyr)
library(ggplot2)
library(gridExtra)

opts_knit$set(root.dir = "../..")

opts_chunk$set(echo = FALSE,
               fig.height = 3, fig.width = 8,
               warning = FALSE,
               messge = FALSE,
               fig.path = NULL)

# Plotting before and after ECDFs to verify that quantile mapping "worked"
# extract legend, code borrowed from SO (for sharing legend between plots)
# https://github.com/hadley/ggplot2/wiki/Share-a-legend-between-two-ggplot2-graphs
g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

# directories
workdir <- opts_knit$get("root.dir")
datadir <- file.path(workdir, "data")
# changepoints
asos_select_adj_dir <- file.path(datadir, "AK_ASOS_stations_adj")
cpts_path <- file.path(asos_select_adj_dir, "cpts_df.Rds")
cpts_df <- readRDS(cpts_path)
# ids of stations to be adjusted
# stations with 1 change point
adj1_stids <- cpts_df$stid[cpts_df$cpts == 1]
# two cp's
adj2_stids <- cpts_df$stid[cpts_df$cpts == 2]
# no cp's
stids_nocpts <- cpts_df$stid[cpts_df$cpts == 0]

theme_set(theme_bw())
# for(i in 1:length(adj1_stids)) {
for(i in 1) {
  asos_path <- file.path(asos_select_adj_dir, 
                         paste0(adj1_stids[i], ".Rds"))
  asos_hourly_station <- readRDS(asos_path)
  
  asos_hourly_station <- mutate(asos_hourly_station, 
                                adj_diff = sped - sped_adj)
  
  asos_hourly_station$period <- as.factor(asos_hourly_station$period)
  xmax <- 7 * summary(asos_hourly_station$sped_adj)[5]
  
  p1 <- ggplot(asos_hourly_station, aes(sped, color = period)) + stat_ecdf(size = 1) + 
    xlab("Wind Speed (MPH)") + ylab("Cumulative Probability") + 
    xlim(c(0, xmax)) + scale_color_discrete(name = "Data", 
                                          labels = c("Biased", "Current")) + 
    theme(legend.position = "bottom") + ggtitle(adj1_stids[i])

  p2 <- ggplot(asos_hourly_station, aes(sped_adj, color = period)) + stat_ecdf(size = 1) + 
    xlab("Wind Speed (MPH)") + ylab(element_blank()) + 
    xlim(c(0, xmax))  + ggtitle(" ")
  
  mylegend <- g_legend(p1)
  
  #barfill <- "gold1"
  #barlines <- "goldenrod2"
  #p3 <- ggplot(asos_hourly_station, aes(x = adj_diff)) +
  #  geom_histogram(aes(y = ..count..), binwidth =  0.5,
  #                 colour = barlines, fill = barfill) +
  #  scale_x_continuous(name = "Adjusted differences",
  #                     breaks = seq(0, 10, 5),
  #                     limits=c(0, 10)) +
  #  scale_y_continuous(name = "Count") +
  #  ggtitle(" ")

  p4 <- grid.arrange(arrangeGrob(p1 + theme(legend.position="none"),
                           p2 + theme(legend.position="none"), 
                           nrow=1),
               mylegend, nrow=2,heights=c(10, 1))
  
}


# for(i in 1:length(adj2_stids)) {
for(i in 1) {

  asos_path <- file.path(asos_select_adj_dir, 
                         paste0(adj2_stids[i], ".Rds"))
  asos_hourly_station <- readRDS(asos_path)
  
  asos_hourly_station <- mutate(asos_hourly_station, 
                                adj_diff = sped - sped_adj)
  
  asos_hourly_station$period <- as.factor(asos_hourly_station$period)
  xmax <- 7 * summary(asos_hourly_station$sped_adj)[5]
  
  p1 <- ggplot(asos_hourly_station, aes(sped, color = period)) + stat_ecdf(size = 1) + 
    xlab("Wind Speed (MPH)") + ylab("Cumulative Probability") + 
    xlim(c(0, xmax)) + scale_color_discrete(name = "Data", 
                                          labels = c("Biased 1", "Biased 2", "Current")) + 
    theme(legend.position = "bottom") + ggtitle(adj1_stids[i])

  p2 <- ggplot(asos_hourly_station, aes(sped_adj, color = period)) + stat_ecdf(size = 1) + 
    xlab("Wind Speed (MPH)") + ylab(element_blank()) + 
    xlim(c(0, xmax))  + ggtitle(" ")
  
  mylegend <- g_legend(p1)
  
  #barfill <- "gold1"
  #barlines <- "goldenrod2"
  #p3 <- ggplot(asos_hourly_station, aes(x = adj_diff)) +
  #  geom_histogram(aes(y = ..count..), binwidth =  0.5,
  #                 colour = barlines, fill = barfill) +
  #  scale_x_continuous(name = "Adjusted differences",
  #                     breaks = seq(0, 10, 5),
  #                     limits=c(0, 10)) +
  #  scale_y_continuous(name = "Count") +
  #  ggtitle(" ")

  p4 <- grid.arrange(arrangeGrob(p1 + theme(legend.position="none"),
                           p2 + theme(legend.position="none"), 
                           nrow=1),
               mylegend, nrow=2,heights=c(10, 1))
  
}

```


```{r move}
# move output file to document directory
files <- list.files(file.path(workdir, "code/ASOS"))
index <- grep("pdf", files)
file.rename(file.path("code", files[index]),
            file.path("documents", files[index]))
```
